set foldmethod=marker   " Set folding by marker
set foldmarker={{{,}}}  " Define the fold markers
set foldlevelstart=99   " Open all folds by default

" General settings {{{
" Disable compatibility mode
set nocp

" Line numbers and search settings
set nu                 " Show line numbers
set hls                " Highlight search results
set incsearch          " Incremental search
:winpos 0 0	       " Window position

" Syntax highlighting and filetype settings
syntax on              " Enable syntax highlighting
filetype indent on     " Enable filetype-specific indentation
filetype plugin on     " Enable filetype-specific plugins

" Disable backup files
set nobackup
set nowritebackup
" }}}

" GUI and display options {{{
set guioptions-=mrLtT   " Remove unwanted GUI elements
set lines=15 columns=9999 " Set window size
set bg=light           " Set background to light
set enc=utf-8          " Set encoding to UTF-8
set fencs=utf-8,cp936,big5,iso-8859-1  " Set file encoding options
" }}}

" Markdown-specific settings {{{
autocmd FileType markdown setlocal spell
autocmd FileType markdown setlocal wrap
autocmd FileType markdown setlocal shiftwidth=2
autocmd FileType markdown setlocal expandtab
autocmd FileType markdown setlocal tabstop=2
autocmd FileType markdown setlocal softtabstop=2
" }}}

" Plugins {{{
" Plugin manager initialization
call plug#begin('~/.vim/plugged')

" CoC plugin with additional language support
Plug 'neoclide/coc.nvim', {'branch': 'release', 'do': 'cd ~/.vim/plugged/coc.nvim && npm install -g coc-vimtex coc-markdown coc-json coc-python coc-css'}
" Map Enter to complete the first item in the completion menu
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"

" NERDTree configuration {{{
Plug 'preservim/nerdtree'
Plug 'xuyuanp/nerdtree-git-plugin'
let g:NERDTreeWinSize=25
let g:NERDTreeShowBookmarks=1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeIgnore = ['\.pyc$']

" Auto open NERDTree when Vim starts
"autocmd vimenter * if !argc() | NERDTree | endif
" Auto quit NERDTree when it is the last buffer
autocmd bufenter * if (winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()) | q | endif
" }}}

" Color schemes and status bar configuration {{{
Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline_theme='solarized'
let g:airline_solarized_bg='light'
set guifont=DejaVu_Sans_Mono_for_Powerline:h16:cANSI:qDRAFT
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
" }}}

" UltiSnips configuration for snippets {{{
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"
" }}}

" Vim-Lastplace configuration {{{
Plug 'farmergreg/vim-lastplace'
let g:lastplace_ignore = "gitcommit,gitrebase,hgcommit,svn,xxd"
let g:lastplace_ignore_buftype = "help,nofile,quickfix"
"}}}

" End plugin manager block
call plug#end()
" }}}

" Set colorscheme {{{
silent! colorscheme solarized
" }}}

" Window and clipboard key mappings {{{
nnoremap nw <c-w><c-w>  " Switch windows
noremap ;p "*p          " Paste from clipboard
noremap ;x "*y          " Yank to clipboard
nnoremap ;d :silent !start explorer.exe "<C-R>=expand('%:p:h')<CR>"<CR> "open the current buffer's directory in Explorer
" }}}

" Airline symbols customization {{{
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_symbols.left_sep = '▶'
let g:airline_symbols.right_sep = '◀'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.linenr = '☰'
let g:airline_symbols.maxlinenr = '㏑'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.whitespace = 'Ξ'
let g:airline_symbols.readonly = ''
let g:airline_symbols.dirty = '⚡'
" }}}

" Python 3 configuration {{{
let &pythonthreedll='C:\Users\vanabel\.pyenv\pyenv-win\versions\3.11.9-win32\python3.dll'
" let &pythondll='C:\Users\vanabel\.pyenv\pyenv-win\versions\2.7.6-win32\python27.dll' " Uncomment if needed
"}}}
