name: Deploy PDFs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'MathSoftwear/out/**'
      - 'MathSoftwear/*.md'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Create directory for deployment
        run: mkdir -p publish

      - name: Copy PDF files from MathSoftwear
        run: |
          find MathSoftwear/out -name "*.pdf" -exec cp {} publish/ \;

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          publish_dir: ./publish
