name: Deploy PDFs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'MathSoftwear/out/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create directory for deployment
        run: mkdir -p publish

      - name: Copy PDF files from MathSoftwear
        run: |
          find MathSoftwear/out -name "*.pdf" -exec cp {} publish/ \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
