name: Export Markdown to PDF

on:
  push:
    paths:
      - 'MathSoftwear/**/*.md'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  export_to_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install obsidian-album
      run: npm install -g obsidian-album

    - name: Run obsidian-album help
      run: npx obsidian-album create --help

    - name: Check output directory
      run: ls -al ./MathSoftwear/out/

    - name: Run obsidian-album to export PDF
      run: |
        npx obsidian-album create \
        --verbose \
        --vault '.' \
        --subFolder 'MathSoftwear' \
        --filterBy '前言.md' \
        --title '数学软件讲义' ./MathSoftwear/out/MathSoftwear.pdf

    - name: Check output directory
      run: ls -al ./MathSoftwear/out/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./MathSoftwear/out
        publish_branch: gh-pages
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'
