name: Export Markdown to PDF

on:
  push:
    paths:
      - 'MathSoftwear/**/*.md'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  export_to_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install obsidian-album
      run: npm install -g obsidian-album

    - name: Run obsidian-album to export PDF
      run: |
        obsidian-album create 数学软件授课讲义.pdf \
          --vault './MathNotes' \
          --subFolder 'MathSoftwear' \
          --filterBy '.md' \
          --title '数学软件讲义'
